//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRest_vPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMOVIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTOMOVIL()
        {
            this.ORDENTRABAJOENCAB = new HashSet<ORDENTRABAJOENCAB>();
        }
    
        public int IDAUTO { get; set; }
        public int IDUSU { get; set; }
        public int IDMODELO { get; set; }
        public string COLORAUTO { get; set; }
        public string PLACAAUTO { get; set; }
        public int KILOMAUTO { get; set; }
        public int ANIO { get; set; }
        public string TRANSMICION { get; set; }
        public string TIPOCOMBUSTIBLE { get; set; }
    
        public virtual MODELO MODELO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENTRABAJOENCAB> ORDENTRABAJOENCAB { get; set; }
    }
}
