//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRest_vPrueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TecniMecanica_vPruebaEntities2 : DbContext
    {
        public TecniMecanica_vPruebaEntities2()
            : base("name=TecniMecanica_vPruebaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOMOVIL> AUTOMOVIL { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<ESTADOORDEN> ESTADOORDEN { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<ORDENTRABAJODET> ORDENTRABAJODET { get; set; }
        public virtual DbSet<ORDENTRABAJOENCAB> ORDENTRABAJOENCAB { get; set; }
        public virtual DbSet<REPUESTO> REPUESTO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
