//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRest_vPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENTRABAJOENCAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENTRABAJOENCAB()
        {
            this.ORDENTRABAJODET = new HashSet<ORDENTRABAJODET>();
        }
    
        public int IDORDENCLI { get; set; }
        public int IDAUTO { get; set; }
        public int IDESTADO { get; set; }
        public int IDUSU { get; set; }
        public string FECHAORDEN { get; set; }
        public string COMENTARIOCLI { get; set; }
        public string INVENTARIOVEHIC { get; set; }
        public string DANIOSAUTOCLI { get; set; }
        public int KILOMAUTOCLI { get; set; }
        public string FALLASAUTOCLI { get; set; }
        public Nullable<bool> TRABFINALIZADO { get; set; }
    
        public virtual AUTOMOVIL AUTOMOVIL { get; set; }
        public virtual ESTADOORDEN ESTADOORDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENTRABAJODET> ORDENTRABAJODET { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
