//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRest_vPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENTRABAJODET
    {
        public int IDORDENDET { get; set; }
        public Nullable<int> IDSERVICIO { get; set; }
        public int IDORDENCLI { get; set; }
        public Nullable<int> IDREPUESTO { get; set; }
        public Nullable<double> TIEMPSERVHORAS { get; set; }
        public int CANTORDENDET { get; set; }
        public double PRECIOORDENDET { get; set; }
        public string DESCRIPCIONDET { get; set; }
    
        public virtual ORDENTRABAJOENCAB ORDENTRABAJOENCAB { get; set; }
        public virtual REPUESTO REPUESTO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
